name: Bug report
description: Report something that does not work as expected
labels: [bug]
assignees: [t28hub]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened
      description: What you did and what actually happened.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: What you expected
      description: What you expected to happen instead.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to ...
        2. Click ...
        3. See the error
    validations:
      required: false
